# Schema for the views plugins of this module.

views.display.views_block_override:
  type: views.display.block
  label: 'Views block override options'
  mapping:
    allow:
      type: mapping
      label: 'Allow'
      mapping:
        exposed_sort:
          type: boolean
          label: 'Expose sort'
        contextual_filter:
          type: boolean
          label: 'Contextual filters'
